administor/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [path('admin/', admin.site.urls)]

admin_torcms/models.py
from django.db import models


class TabTag(models.Model):
    uid = models.CharField(
        null=False,
        max_length=4,
        # db_index =True,
        unique=True,
        primary_key=True,
        help_text='',
    )
    slug = models.CharField(
        null=False,
        # db_index =True,
        unique=True,
        max_length=36,
        help_text='',
    )
    name = models.CharField(null=False, max_length=255, help_text='')
    order = models.IntegerField()
    count = models.IntegerField(default=0)
    kind = models.CharField(
        null=False,
        max_length=1,
        default='z',
        help_text='4 - f for category. g -  for tags',
    )
    # 'xxxx' for unkonw, 'zzzz' for tag.
    pid = models.CharField(
        null=False, max_length=4, default='xxxx', help_text='parent id'
    )
    tmpl = models.IntegerField(null=False, default='9', help_text='tmplate type')

    class Meta:
        db_table = 'tabtag'
        verbose_name = "Tags"
        ordering = ['uid']
        verbose_name_plural = verbose_name
        indexes = [
            models.Index(fields=['slug'], name='tabtag_slug'),
        ]


class TabLink(models.Model):
    uid = models.CharField(
        null=False,
        # index=False,
        unique=True,
        primary_key=True,
        default='0000',
        max_length=4,
        help_text='',
    )
    link = models.CharField(null=False, max_length=255, help_text='')
    name = models.CharField(null=False, max_length=255, help_text='')
    logo = models.CharField(null=False, max_length=255, help_text='')
    order = models.IntegerField()

    class Meta:
        db_table = 'tablink'
        verbose_name = "Links"
        ordering = ['uid']
        verbose_name_plural = verbose_name


class TabPost(models.Model):
    uid = models.TextField(
        null=False,
        # db_index =True,
        unique=True,
        primary_key=True,
        default='00000',
        help_text='',
    )
    title = models.CharField(null=False, max_length=255, help_text='Title')
    keywords = models.CharField(
        null=False, max_length=255, default='', help_text='Keywords'
    )
    date = models.DateTimeField(null=False, max_length=255, help_text='')
    time_create = models.IntegerField()
    user_name = models.CharField(
        null=False, default='', max_length=255, help_text='UserName'
    )
    time_update = models.IntegerField()
    view_count = models.IntegerField(default=0)

    access_1d = models.IntegerField(default=0, help_text='24小时内阅读量')
    access_7d = models.IntegerField(default=0, help_text='7*24小时内阅读量')
    access_30d = models.IntegerField(default=0, help_text='30*24小时内阅读量')

    logo = models.CharField(
        default='',
        max_length=255,
    )
    order = models.CharField(null=False, default='', max_length=8)
    valid = models.IntegerField(
        null=False, default=1, help_text='Whether the infor would show.'
    )
    cnt_md = models.TextField()
    cnt_html = models.TextField()
    kind = models.CharField(null=False, max_length=1, default='1', help_text='app type')
    state = models.CharField(
        null=False,
        max_length=4,
        default='0000',
        help_text='state for post. 发布/审核状态.',
    )
    rating = models.FloatField(null=False, default=5, help_text='Rating of the post.')
    memo = models.TextField(null=False, default='', help_text='Memo')
    extinfo = models.JSONField(null=True, default={}, help_text='Extra data in JSON.')

    class Meta:
        db_table = 'tabpost'
        verbose_name = "TabPost"
        ordering = ['uid']
        verbose_name_plural = verbose_name
        indexes = [
            models.Index(fields=['extinfo'], name='tabpost_extinfo'),
        ]


class TabWiki(models.Model):
    # slug for page, and '_12345678' for wiki.
    uid = models.CharField(
        null=False,
        # db_index =True,
        unique=True,
        primary_key=True,
        max_length=36,
        help_text='',
    )
    title = models.CharField(
        null=False,
        unique=True,
        # db_index =True,
        help_text='Title',
        max_length=255,
    )
    date = models.DateTimeField()
    time_create = models.IntegerField()
    user_name = models.CharField(null=False, max_length=255, help_text='UserName')
    time_update = models.IntegerField()
    view_count = models.IntegerField()
    cnt_md = models.TextField()
    cnt_html = models.TextField()
    kind = models.CharField(
        null=False, max_length=1, default='1', help_text='1 for wiki, 2 for page.'
    )

    class Meta:
        db_table = 'tabwiki'
        verbose_name = "wiki"
        ordering = ['uid']
        verbose_name_plural = verbose_name


class TabPostHist(models.Model):
    '''
    Table for post history.
    '''

    uid = models.CharField(
        null=False,
        # db_index =True,
        unique=True,
        help_text='',
        primary_key=True,
        max_length=36,
    )
    title = models.CharField(null=False, max_length=255, help_text='')
    post = models.ForeignKey(
        TabPost,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        db_constraint=False,
        db_column='post_id',
    )

    user_name = models.CharField(
        max_length=255,
    )
    cnt_md = models.TextField()
    time_update = models.IntegerField()
    logo = models.CharField(
        max_length=255,
    )

    class Meta:
        db_table = 'tabposthist'
        verbose_name = "PostHist"
        ordering = ['uid']
        verbose_name_plural = verbose_name


class TabWikiHist(models.Model):
    '''
    Table for wiki history.
    '''

    uid = models.CharField(
        null=False,
        # db_index =True,
        unique=True,
        help_text='',
        primary_key=True,
        max_length=36,
    )
    title = models.CharField(null=False, max_length=255, help_text='')
    # wiki_id = models.CharField(null=False, max_length=36, help_text='')
    wiki = models.ForeignKey(
        TabWiki, null=True, blank=True, on_delete=models.SET_NULL, db_constraint=False
    )
    user_name = models.CharField(
        max_length=255,
    )
    cnt_md = models.TextField()
    time_update = models.IntegerField()

    class Meta:
        db_table = 'tabwikihist'
        verbose_name = "WikiHist"
        ordering = ['uid']
        verbose_name_plural = verbose_name


class TabMember(models.Model):
    '''
    role:  the index and value should not greater than 3.
    "0123"
    read,add,edit,delete,manage
    [0]: for wiki, and post editing.
    [1]: post create, and management.
    [2]: keep
    [3]: keep
    And, could be extended.
    The Value:
    0: for view
    1: for basic editing
    2: for management
    3:
    '''

    uid = models.CharField(
        null=False,
        # db_index =True,
        unique=True,
        primary_key=True,
        max_length=36,
        help_text='',
    )
    user_name = models.CharField(
        null=False,
        #  # db_index =True,
        unique=True,
        max_length=255,
        help_text='User Name',
    )
    user_email = models.CharField(
        null=False, unique=True, max_length=255, help_text='User Email'
    )
    user_pass = models.CharField(null=False, max_length=255, help_text='User Password')
    is_active = models.SmallIntegerField(null=False, help_text='', default=0)
    is_staff = models.SmallIntegerField(
        null=False, help_text='if 1 then could access backend', default=0
    )
    role = models.CharField(
        null=False, default='1000', help_text='Member Privilege', max_length=4
    )
    '''
    进行审核的权限，与 role 配合使用。
    role 声明是否有权限， authority 声明对哪些 post 有权限。
    post 权限类型由二进制的 '1', '10', '100', '1000', ... 声明 ，成员的 authority 则根据二进制相加的结果来声明多种 post 的审核权限
    ToDo: 设计有问题。应该将采用RBAC进行解耦。
    '''
    authority = models.CharField(
        null=False,
        default='0',
        help_text='Member authority for checking',
        max_length=8,
    )
    time_reset_passwd = models.IntegerField(null=False, default=0)
    time_login = models.IntegerField(null=False, default=0)
    time_create = models.IntegerField(null=False, default=0)
    time_update = models.IntegerField(null=False, default=0)
    time_email = models.IntegerField(
        null=False, default=0, help_text='Time auto send email.'
    )
    failed_times = models.IntegerField(
        null=False, default=0, help_text='record the times for trying login.'
    )
    time_failed = models.IntegerField(
        null=False, default=0, help_text='timestamp for login failed.'
    )
    extinfo = models.JSONField(null=False, default={}, help_text='Extra data in JSON.')

    class Meta:
        db_table = 'tabmember'
        verbose_name = "Member"
        ordering = ['uid']
        verbose_name_plural = verbose_name


class TabEntity(models.Model):
    '''
    Table to store the entity information.
    '''

    uid = models.CharField(
        null=False,
        # db_index =True,
        unique=True,
        primary_key=True,
        max_length=36,
    )
    path = models.CharField(null=False, unique=True, max_length=255, help_text='')
    desc = models.CharField(null=False, default='', max_length=255, help_text='')
    time_create = models.IntegerField()
    kind = models.CharField(
        null=False, max_length=1, default='1', help_text='1 for image'
    )

    class Meta:
        db_table = 'tabentity'
        verbose_name = "Entity"
        ordering = ['uid']
        verbose_name_plural = verbose_name


class TabPost2Tag(models.Model):
    '''
    Table of tag to the post.
    '''

    uid = models.CharField(
        null=False,
        # db_index =True,
        unique=True,
        primary_key=True,
        max_length=36,
        help_text='',
    )
    # par_id = models.CharField(
    #     null=False, default='', max_length=4, help_text='父类id，对于label，top_id为""'
    # )
    # tag_id = models.CharField(null=False, max_length=4, help_text='')

templates/post_1/leaf_view.html
{% autoescape None %}
{% extends "../theme/tmpleaf.html" %}
{% block head %}
<meta name="keywords" content="{{ postinfo.keywords }} ">
<meta name="description" content="{% module generate_abstract(postinfo.cnt_html) %}">

{% end %}
{% block content %}
<ol class="breadcrumb">
    <li>{{ _('Current location') }}: <a href="{% module site_url() %}">{{ _('Home') }}</a></li>
    <li>{% module the_category(postinfo.uid, order=True) %}</li>
    <li class="active">{{ postinfo.title }}</li>
</ol>
<div class="panel panel-primary">
    <div class="panel-heading">
        <h2>{{ postinfo.title }}</h2>
        <span>{{ str(postinfo.date)[:10] }}</span>
        <span>{{ _('Author') }}: <a href="http://www.osgeo.cn/">OSGeo中国中心</a></span>
        <span>{{ _('Browse') }}: {{ postinfo.view_count }} </span>
        {% module widget_editor('post', postinfo.uid, userinfo) %}
    </div>
    <div class="panel-body">
        <div class="entry">
            <p class="summary"><strong>{{ _('Abstract') }}</strong>: {% module generate_abstract(postinfo.cnt_html) %} </p>

            <div class="entrycontent">
                {% raw unescape(postinfo.cnt_html) %}
            </div>
        </div>
        <div class="postmeta">
            <div class="wpyouvote"></div>
            <div class="clear"></div>
            <br>
            <strong>{{ _('Article link') }}:</strong>
            <a href="{% module site_url() %}/post/{{postinfo.uid}}" class="underline"> {{ postinfo.title }}</a>
            <br/>
            <strong>{{ _('Copyright') }}:</strong> {{ _('Non special statement are original articles, reproduced please indicate the  source') }}：
            <a href="http://osgeo.cn" class="underline">OSGeo中国中心</a><br>
        </div>
    </div>
    <p style="border-bottom: 1px dashed #dddddd; margin-bottom: 20px">&nbsp;</p>

    <div class="panel-footer">
        <div class="row">
            <div class="col-sm-6">
                <div class="btn btn-primary">{% module previous_post_link(postinfo.uid) %}</div>
                <div class="btn btn-primary">{% module next_post_link(postinfo.uid) %}</div>
            </div>
            <div class="col-sm-6">
                {% module baidu_share() %}
            </div>
        </div>
    </div>
</div>
{% end %}

templates/post_1/post_add.html
{% extends "../theme/tmpldoc.html" %}
{% block content %}
<ol class="breadcrumb">
   <li>{{ _('Current location') }}: <a href="{% module site_url() %}">{{ _('Home') }}</a></li>
    <li>{{ _('Add document') }}</li>
</ol>
<div class="panel panel-black">
    <div class="panel-heading">
        {{ _('Add document') }}
    </div>
    <div class="panel-body">
        <form action="" method="post" class="form-horizontal" role="form" id="form_post">
            <input type=hidden name=uid value="{{ kwd['uid'] }}">
            <input type=hidden name=valid value="1">
            <fieldset>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="title">{{ _('Title') }}</label>

                    <div class="col-sm-10">
                        <input class="form-control" type="text" id="title" name="title">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="tags">{{ _('Label') }}</label>

                    <div class="col-sm-10">
                        <input id="tags" name="tags" class="form-control" onchange="chuli_kw()">
                            <br>
                            <div id="kwlist"></div>
                    </div>
                </div>


                {% for ii in range(0,5) %}
                <div class="form-group">
                    {% if ii == 0 %}
                    <label for="pcat0" class="col-sm-2 control-label">{{ _('Category') }}</label>
                    {% else %}
                    <label for="pcatx" class="col-sm-2 control-label"></label>
                    {% end %}
                    <div class="col-sm-3">
                        <select name="pcat{{ii}}" id="pcat{{ii}}" class="form-control"
                                onchange="g_load_postcat({{ii}})">
                            <option value="">{{ _('Please select') }}</option>
                            {% for taginfo in tag_infos %}
                            {% if taginfo.uid.endswith('00') %}
                            <option value="{{ taginfo.uid }}">{{ taginfo.name }}
                            </option>
                            {% else %}
                            {% end %}
                            {% end %}
                        </select>
                    </div>
                    <div class="col-sm-4">
                        <select name="gcat{{ii}}" id="gcat{{ii}}" class="form-control">
                        </select>
                    </div>
                </div>
                {% end %}
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="logo">{{ _('Picture') }}</label>

                    <div class="col-sm-10">


                        <input type="text" id="logo" name="logo" class="form-control" readonly/>

                        <br>

                        <a class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
                            {{ _('Upload picture') }}
                        </a>


                    </div>
                </div>

                <div class="form-group">
                    <label class="col-sm-2 control-label" for="cnt_md">{{ _('Content') }} </label>

                    <div class="col-sm-10">
                        <textarea rows=26 id="cnt_md" name="cnt_md" cols="80" class="form-control"></textarea>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-2 control-label" for="sub1"></label>

                    <div class="col-sm-10">
                        <input id="sub1" type="submit" class="btn btn-primary" value="{{ _('Submit') }}"/>
                    </div>
                </div>
            </fieldset>
        </form>
        {% module upload_pic() %}
    </div>
</div>
{% end %}

templates/post_1/post_edit.html
{% extends "../theme/tmpldoc.html" %}
{% block content %}
<ol class="breadcrumb">
      <li>{{ _('Current location') }}: <a href="{% module site_url() %}">{{ _('Home') }}</a></li>
    <li>{{ _('Modify the document') }}</li>
</ol>
<div class="panel panel-black">
    <div class="panel-heading">
        {{ postinfo.title }}-{{ _('Modify the document') }}
    </div>
    <div class="panel-body">
        <form method="post" class="form-horizontal" role="form" id="form_post">
            <fieldset>
                <input type="hidden" id="id_post" name="id_post" value="{{ postinfo.uid }}"/>

                <div class="form-group">
                    <label for="title" class="col-sm-2 control-label">{{ _('Title') }}</label>

                    <div class="col-sm-10">
                        <input type="text" id="title" name="title" value="{{ postinfo.title }}"
                               class="form-control"/>
                    </div>
                </div>


  <div class="form-group">
                    <label class="col-sm-2 control-label" for="tags">{{ _('Label') }}</label>
                    <div class="col-sm-10">
                        <input class="form-control" id="tags" name="tags" type="text"
                               value="{% for x in app2label_info %}
                                    {{ x.tag_name }},
                                    {% end  %}" onchange="chuli_kw()">
                            <br>
                            <div id="kwlist"></div>
                    </div>
                </div>




                {% for ii in range(0,5) %}
                <div class="form-group">
                    {% if ii == 0 %}
                    <label for="pcat0" class="col-sm-2 control-label">{{ _('Category') }}</label>
                    {% else %}
                    <label class="col-sm-2 control-label"></label>
                    {% end %}
                    <div class="col-sm-3">
                        <select name="pcat{{ii}}" id="pcat{{ii}}" class="form-control"
                                onchange="g_load_postcat({{ii}})">
                            <option value="">{{ _('Please select') }}</option>
                            {% for taginfo in tag_infos %}
                            {% if taginfo.uid.endswith('00') %}
                            <option value="{{ taginfo.uid }}"
                                    {% for tt in app2tag_info %}
                                    {% if tt.order== ii and tt.tag_id.startswith(taginfo.uid[:2]) %}
                                    selected
                                    {% end %}
                                    {% end %}>{{ taginfo.name }}
                            </option>
                            {% else %}
                            {% end %}
                            {% end %}
                        </select>
                    </div>

                    <div class="col-sm-4">
                        <select name="gcat{{ii}}" id="gcat{{ii}}" class="form-control">
                            <option value="0">{{ _('Please select') }}</option>
                            {# 设置父类ID，用在下面子类是否显示看 #}
                            {% set pcatid = 'xx' %}
                            {% for taginfo in tag_infos %}
                            {% for tt in app2tag_info %}
                            {% if tt.order== ii and tt.tag_id== taginfo.uid %}
                            {% set pcatid = tt.tag_id[:2] %}
                            {% end %}
                            {% end %}
                            {% end %}

                            {% for taginfo in tag_infos %}
                            {% if taginfo.uid.startswith(pcatid) %}
                            {% if not taginfo.uid.endswith('00') %}
                            <option value="{{ taginfo.uid }}"
                                    {% for tt in app2tag_info %}
                                    {% if tt.order== ii and tt.tag_id== taginfo.uid %}
                                    selected
                                    {% end %}
                                    {% end %}>{{ taginfo.name }}
                            </option>
                            {% else %}
                            {% end %}
                            {% end %}
                            {% end %}

                        </select>
                    </div>

                </div>
                {% end %}

                <div class="form-group">
                    <label for="logo" class="col-sm-2 control-label">{{ _('Picture') }}</label>

                    <div class="col-sm-10">
                        <input id="logo" name="logo" type="text" value="{{ postinfo.logo }}"  class="form-control" readonly />
                        <br>
                        <a class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">{{ _('Upload picture') }}</a>
                    </div>
                </div>

                <div class="form-group">
                    <label for="cnt_md" class="col-sm-2 control-label">{{ _('Content') }}</label>

                    <div class="col-sm-10">
                        <textarea rows=26 id="cnt_md" name="cnt_md" class="form-control">
                            {% raw unescape(postinfo.cnt_md) %}
                        </textarea>
                    </div>
                </div>
{#                 <div class="form-group">#}
{#                    <label class="col-sm-2 control-label" for="valid">{{ _('Is available') }}</label>#}
{##}
{#                    <div class="col-sm-10">#}
{#                        <select name="valid" id="valid" class="form-control">#}
{#                            <option value="1" {% if postinfo.valid == 1 %} selected {% end %} >{{ _('yes') }}</option>#}
{#                            <option value="0" {% if postinfo.valid == 0 %} selected {% end %} >{{ _('no') }}</option>#}
{#                        </select>#}
{#                    </div>#}
{#                </div>#}
                <div class="form-group">
                    <label for="is_update_time" class="col-sm-2 control-label">{{ _('Update edit time') }}</label>

                    <div class="col-sm-10">
                        <input id="is_update_time" type="radio" name="is_update_time" value="1">{{ _('To update') }}
                        <input id="is_update_time" type="radio" name="is_update_time" value="0" checked>{{ _('Not updated') }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="sub1" class="col-sm-2 control-label"></label>

                    <div class="col-sm-10">
                        <input id="sub1" type="submit" class="btn btn-primary" value="{{ _('Sumbit') }}"/>
                    </div>
                </div>
                <hr/>
            <div class="form-group">
                <label class="col-sm-2 control-label">
                    <a class="glyphicon glyphicon-star" style="color: red;font-size: xx-small;"></a>
                    JSON
                </label>

                <div class="col-sm-10">
                    <textarea class="form-control" rows=26 id="json" name="json" readonly="readonly">
                        {{ kwd['extinfo'] }}
                    </textarea>
                </div>
            </div>
            </fieldset>
        </form>
          {% module upload_pic() %}
    </div>
</div>
{% end %}

templates/post_1/post_index.html
{% extends "../theme/bage.html" %}
{% block typebody %}
<div class="row">
    <div class="col-sm-9">
        <div class="row">
            <div class="col-sm-4">
                <div class="panel panel-black">
                    {% module post_catalog_of('0100',slug=True) %}
                </div>
            </div>
            <div class="col-sm-4">
                <div class="panel panel-black">
                    {% module post_catalog_of('0200',slug=True) %}
                </div>

            </div>

        </div>
    </div>
    <div class="col-sm-3">
        <div class="panel panel-black">
            <div class="panel-heading">
                <h3 class="panel-title">
                    {{ _('Most concern') }}
                </h3>
            </div>
            <ul class="list-group" id="mostall">
                {% module post_most_view(5, with_date = False, with_catalog= False) %}
            </ul>
        </div>
        <div class="panel panel-black">
            <div class="panel-heading">
                <h3 class="panel-title">
                    {{ _('Recent articles') }}
                </h3>
            </div>
            <ul class="list-group">
                {% module post_recent(5, with_date = False, with_catalog= False) %}
            </ul>
        </div>
    </div>
</div>
<br>
{% end %}

templates/post_1/post_list.html
{% extends "../theme/tmpldoc.html" %}
{% block content %}
<ol class="breadcrumb">
   <li>{{ _('Current location') }}: <a href="{% module site_url() %}">{{ _('Home') }}</a></li>
    <li><a href="/post/recent"> {{ _('Document list') }}</a></li>
</ol>
<div class="panel panel-black">
    <div class="panel-heading">{{ _('Document list') }}</div>
    <ul class="list-group">
        {% for x in view %}
        <li class="list-group-item">
            <a href="/post/{{ x.uid }}" title="{{ x.title }}">
                {{ x.title }}
            </a>

            <span>{{ datetime.datetime.fromtimestamp(x.time_update).strftime('%Y-%m-%d %H:%M:%S') }}</span>
        </li>
        {% end %}
    </ul>
    <div class="clear"></div>
    <div>
        <ul class="pagination">
            {% raw kwd['pager'] %}
        </ul>
    </div>
</div>
{% end %}

templates/post_1/post_view.html
{% autoescape None %}
{% extends "../theme/tmpldoc.html" %}
{% block head %}
<meta name="keywords" content="{{ postinfo.keywords }} ">
{#<meta name="description" content="{% module generate_abstract(postinfo.cnt_html) %}">#}

{% end %}
{% block content %}

<ol class="breadcrumb">
   <li>{{ _('Current location') }}: <a href="{% module site_url() %}">{{ _('Home') }}</a></li>
        <li><a href="/{{router}}/" title="{{post_type}}">{{post_type}}</a></li>
    <li>{% module the_category(postinfo.uid) %}</li>
    <li class="active">{{ _('Text') }}</li>
</ol>
<div class="panel panel-black">
    <div class="panel-heading">
        <h3 class="listinfo_title">{{ postinfo.title }}</h3>
        <span class="split">  {{ _('Author') }} : {{ postinfo.user_name }} </span>&nbsp;
        <span>{{ datetime.datetime.fromtimestamp(postinfo.time_create).strftime('%Y-%m-%d %H:%M:%S')}}</span>
        <span>{{ _('Browse') }}: {{ postinfo.view_count }} </span>
        {% if userinfo %}
          {% module collect(userinfo.uid, postinfo.uid,en=True) %}
        {% end %}
        {% module widget_editor(kwd['router'], postinfo.uid, userinfo,kind=postinfo.kind) %}
    </div>
    <div class="panel-body">

        <div class="entry">
            <div class="bor_bottom">
                <b>{{ _('Category') }} :</b> <span class="post_cat">{% module post_catalogs(postinfo.uid,'1') %}</span>
            </div>
            <p class="summary"><strong>{{ _('Abstract') }}</strong>: {% module generate_abstract(postinfo.cnt_html) %} </p>

            <div class="entrycontent">
                {% raw unescape(postinfo.cnt_html) %}
            </div>
            <div class="bor_bottom">
                <b>{{ _('Label') }} :</b>
        <span class="post_label">
             {% module post_labels(post_uid = postinfo.uid) %}
        </span>
            </div>
            <div class="listinfo_content">
                {% module reply_panel(postinfo.uid, userinfo, en=True) %}
            </div>
        </div>

        <div class="postmeta">
            <div class="wpyouvote"></div>
            <div class="clear"></div>
            <br>
            <strong>{{ _('Article link') }}:</strong>
            <a href="{% module site_url() %}/{{kwd['router']}}/{{postinfo.uid}}" class="underline"> {{ postinfo.title }}</a>
            <br/>
            <strong>{{ _('Copyright') }}:</strong> {{ _('Non special statement are original articles, reproduced please indicate the  source') }}
        </div>
    </div>
    <div class="panel-footer">
        <div class="row">
            <div class="col-sm-12">
                <div class="btn btn-primary">{% module previous_post_link(postinfo.uid) %}</div>
                <div class="btn btn-primary">{% module next_post_link(postinfo.uid) %}</div>
            </div>

        </div>
    </div>
</div>

<div class="panel panel-black">
    <div class="panel-heading"><h3 class="panel-title">{{ _('Related') }}</h3></div>
    <ul class="list-group" style="overflow: hidden;">
        {% for x in relations %}
        <li class="list-group-item" style="overflow: hidden;">
            <a href="/{{kwd['router']}}/{{ x.post_id }}">
               {{ x.post_title }}
                {% if x.post_id[0] == 'v' %}<span class="badge" style="color:yellow">v</span>{% end %}
            </a>
        </li>
        {% end %}

    </ul>
</div>
{% end %}